- name: integration of terraform and ansible
  hosts: localhost

  tasks:
  - name: installing httpd
    package:
         name: httpd
         state: present
  - name: install flask with pip
    pip: name=flask
  - name: installing php
    package:
         name: php
         state: present
  - name: starting httpd service
    service:
         name: httpd
         state: started
  - name: installing git
    package:
         name: git
         state: present
  - name: formatting storage
    filesystem:
            fstype: ext4
            dev : /dev/xvdh
  - name: making folder
    file:
         path: /var/www/html/web
         state: directory

  - name: mounting storage
    mount:
        fstype: ext4
        src: /dev/xvdh
        path: /var/www/html
        state: mounted

  - name: cloning git repo
    ansible.builtin.git:
            repo: "https://github.com/alexisundas/WeatherWebApp.git"
            dest: /var/www/html/web